apiVersion: v1
kind: Service
metadata:
  name: twtweb-service
  labels:
    name: twtweb-service
    app: twtweb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: twtweb
    app: twtweb
